## GA-8 (Part-B)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import BaggingRegressor, RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor

In [ ]:
data = pd.read_csv('https://drive.google.com/uc?export=download&id=1tKqddJuIiRqrm7ml2qyVGJlAW3JQjaZX')
data

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208,20,27,3823,109,186

In [ ]:
X= data.dropna()
y = X.loc[:,'MSRP']
X = X.drop('MSRP', axis=1).drop('Invoice', axis=1)
y = y.replace('[\$\,]','', regex=True).astype(int)

In [ ]:
X

,Make,Model,Type,Origin,DriveTrain,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,3.5,6.0,225,18,24,3880,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,2.5,5.0,208,20,27,3823,109,186

In [ ]:
y

0      36945
1      23820
2      26990
3      33195
4      43755
       ...
423    40565
424    42565
425    45210
426    26135
427    35145
Name: MSRP, Length: 426, dtype: int64

In [ ]:
cat_feat = ['Make','Model','Type','Origin', 'DriveTrain']
X_f = pd.get_dummies(X, columns=cat_feat)
X_f

,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Make_Acura,Make_Audi,...,Type_Sedan,Type_Sports,Type_Truck,Type_Wagon,Origin_Asia,Origin_Europe,Origin_USA,DriveTrain_All,DriveTrain_Front,DriveTrain_Rear
0,3.5,6.0,265,17,23,4451,106,189,1,0,...,0,0,0,0,1,0,0,1,0,0
1,2.0,4.0,200,24,31,2778,101,172,1,0,...,1,0,0,0,1,0,0,0,1,0
2,2.4,4.0,200,22,29,3230,105,183,1,0,...,1,0,0,0,1,0,0,0,1,0
3,3.2,6.0,270,20,28,3575,108,186,1,0,...,1,0,0,0,1,0,0,0,1,0
4,3.5,6.0,225,18,24,3880,115,197,1,0,...,1,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,2.4,5.0,197,21,28,3450,105,186,0,0,...,1,0,0,0,0,1,0,0,1,0
424,2.3,5.0,242,20,26,3450,105,186,0,0,...,1,0,0,0,0,1,0,0,1,0
425,2.9,6.0,268,19,26,3653,110,190,0,0,...,1,0,0,0,0,1,0,0,1,0
426,1.9,4.0,170,22,29,2822,101,180,0,0,...,0,0,0,1,0,1,0,0,1,0
427,2.5,5.0,208,20,27,3823,109,186,0,0,...,0,0,0,1,0,1,0,1,0,0

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_f, y, test_size=0.3, random_state = 1)

In [ ]:
br = BaggingRegressor(random_state = 1)
rfr = RandomForestRegressor(random_state = 1)
gbr = GradientBoostingRegressor(random_state = 1)
abr = AdaBoostRegressor(random_state = 1)
br.fit(X_train,y_train)
rfr.fit(X_train,y_train)
gbr.fit(X_train,y_train)
abr.fit(X_train,y_train)

AdaBoostRegressor(random_state=1)

In [ ]:
print(br.score(X_test,y_test))
print(rfr.score(X_test,y_test))
print(gbr.score(X_test,y_test))
print(abr.score(X_test,y_test))

0.7949163237522345
0.8369440882741959
0.8270485242007507
0.711903287964231

In [ ]:
param_grid = {'n_estimators':[100,500,1000], 'learning_rate':[0.5,1,2]}
gscv = GridSearchCV(abr, param_grid=param_grid, cv=4)
gscv.fit(X_train, y_train)

GridSearchCV(cv=4, estimator=AdaBoostRegressor(random_state=1),
             param_grid={'learning_rate': [0.5, 1, 2],
                         'n_estimators': [100, 500, 1000]})

In [ ]:
gscv.score(X_test, y_test)

0.7130800769863186

In [ ]:
gscv.best_params_

{'learning_rate': 1, 'n_estimators': 1000}